export default {
    FeatureName: 'M@S Studio AHome Promoted Plans',
    features: [
        {
            tcid: '0',
            name: '@studio-promoted-plans-editor',
            path: '/studio.html',
            data: {
                cardid: '031e2f50-5cbc-4e4b-af9b-c63f0e4f2a93',
            },
            browserParams: '#query=',
            tags: '@mas-studio @ahome @ahome-promoted-plans @ahome-promoted-plans-edit nopr',
        },
        {
            tcid: '1',
            name: '@studio-promoted-plans-edit-title',
            path: '/studio.html',
            data: {
                cardid: '031e2f50-5cbc-4e4b-af9b-c63f0e4f2a93',
                oldTitle: 'Creative Cloud All Apps',
                updatedTitle: 'Creative Cloud All Apps Long title test example',
                newTitle: 'Creative Cloud All Apps Long title te...',
            },
            browserParams: '#query=',
            tags: '@mas-studio @ahome @ahome-promoted-plans @ahome-promoted-plans-edit',
        },
        {
            tcid: '2',
            name: '@studio-promoted-plans-edit-gradient-border',
            path: '/studio.html',
            data: {
                cardid: '031e2f50-5cbc-4e4b-af9b-c63f0e4f2a93',
                gradientBorderColor: 'gradient',
                gradientBorderCSSColor:
                    'linear-gradient(135deg, #ff4885 0%, #b272eb 50%, #5d89ff 100%)',
                standardBorderColor: 'spectrum-gray-200',
                standardBorderCSSColor: 'var(--spectrum-gray-200)',
            },
            browserParams: '#query=',
            tags: '@mas-studio @ahome @ahome-promoted-plans @ahome-promoted-plans-edit',
        },
        {
            tcid: '3',
            name: '@studio-promoted-plans-edit-description',
            path: '/studio.html',
            data: {
                cardid: '031e2f50-5cbc-4e4b-af9b-c63f0e4f2a93',
                description:
                    'Create with Adobe on the web. Includes Firefly, Express, Photoshop, Lightroom, and more.',
                updatedDescription:
                    'Create with Adobe on the web. Get access to Firefly, Express, Photoshop, and more creative tools.',
            },
            browserParams: '#query=',
            tags: '@mas-studio @ahome @ahome-promoted-plans @ahome-promoted-plans-edit',
        },
        {
            tcid: '4',
            name: '@studio-promoted-plans-edit-icon',
            path: '/studio.html',
            data: {
                cardid: '031e2f50-5cbc-4e4b-af9b-c63f0e4f2a93',
                iconURL:
                    'https://www.adobe.com/cc-shared/assets/img/product-icons/svg/creative-cloud.svg',
                iconAlt: 'Creative Cloud All Apps',
                updatedIconURL:
                    'https://www.adobe.com/content/dam/shared/images/product-icons/svg/acrobat.svg',
                updatedIconAlt: 'Adobe Acrobat',
            },
            browserParams: '#query=',
            tags: '@mas-studio @ahome @ahome-promoted-plans @ahome-promoted-plans-edit',
        },
        {
            tcid: '5',
            name: '@studio-promoted-plans-edit-price',
            path: '/studio.html',
            data: {
                cardid: '031e2f50-5cbc-4e4b-af9b-c63f0e4f2a93',
                originalPrice: 'US$79.99/mo',
                updatedPrice: 'US$15.99/mo',
                originalStrikethroughPrice: 'US$79.99/mo',
                updatedStrikethroughPrice: 'US$22.99/mo',
                recurrenceText: 'Annual, paid monthly',
                updatedRecurrenceText: 'Annual plan, paid monthly',
                osi: 'Mutn1LYoGojkrcMdCLO7LQlx1FyTHw27ETsfLv0h8DQ',
                updatedOsi: 'eCnyzS8MdPPGcIRelbXn_qGjQlg0nFjtPDPmS4pDf6A',
            },
            browserParams: '#query=',
            tags: '@mas-studio @ahome @ahome-promoted-plans @ahome-promoted-plans-edit',
        },
        {
            tcid: '6',
            name: '@studio-promoted-plans-edit-cta',
            path: '/studio.html',
            data: {
                cardid: '031e2f50-5cbc-4e4b-af9b-c63f0e4f2a93',
                termsText: 'See terms',
                updatedTermsText: 'See terms',
                termsLink: 'https://adobe.com',
                updatedTermsLink: 'https://adobe.com/terms',
                freeTrialButtonText: 'Free trial',
                updatedFreeTrialText: 'Try free',
                buyButtonText: 'Buy now',
                updatedBuyText: 'Purchase',
                buyButtonVariant: 'accent',
                updatedBuyButtonVariant: 'primary',
                osi: 'Mutn1LYoGojkrcMdCLO7LQlx1FyTHw27ETsfLv0h8DQ',
                ucv3: 'commerce.adobe.com/store/email',
                country: 'US',
                ctx: 'fp',
                lang: 'en',
                client: 'adobe_com',
            },
            browserParams: '#query=',
            tags: '@mas-studio @ahome @ahome-promoted-plans @ahome-promoted-plans-edit',
        },
        {
            tcid: '7',
            name: '@studio-promoted-plans-acrobat-card',
            path: '/studio.html',
            data: {
                cardid: 'c802c222-a573-42ed-a217-301daf2e05d2',
                title: 'Adobe Acrobat',
                description:
                    'The complete PDF solution for a mobile, connected world.',
                iconURL:
                    'https://www.adobe.com/content/dam/shared/images/product-icons/svg/acrobat.svg',
                iconAlt: 'Adobe Acrobat',
                price: 'US$15.99/mo',
                strikethroughPrice: 'US$22.99/mo',
                recurrenceText: 'Annual, paid monthly',
                borderColor: 'spectrum-gray-200',
                borderCSSColor: 'var(--spectrum-gray-200)',
                buyButtonVariant: 'primary',
                osi: 'eCnyzS8MdPPGcIRelbXn_qGjQlg0nFjtPDPmS4pDf6A',
            },
            browserParams: '#query=',
            tags: '@mas-studio @ahome @ahome-promoted-plans @ahome-promoted-plans-edit',
        },
    ],
};
