export default {
    FeatureName: 'M@S Studio CCD Suggested',
    features: [
        {
            tcid: '0',
            name: '@studio-suggested-discard-edited-title',
            path: '/studio.html',
            data: {
                cardid: '206a8742-0289-4196-92d4-ced99ec4191e',
                title: 'Automation Test Card',
                newTitle: 'Change title',
            },
            browserParams: '#query=',
            tags: '@mas-studio @ccd @ccd-suggested @ccd-suggested-discard',
        },
        {
            tcid: '1',
            name: '@studio-suggested-discard-edited-eyebrow',
            path: '/studio.html',
            data: {
                cardid: '206a8742-0289-4196-92d4-ced99ec4191e',
                subtitle: 'do not edit',
                newSubtitle: 'Change subtitle',
            },
            browserParams: '#query=',
            tags: '@mas-studio @ccd @ccd-suggested @ccd-suggested-discard',
        },
        {
            tcid: '2',
            name: '@studio-suggested-discard-edited-description',
            path: '/studio.html',
            data: {
                cardid: '206a8742-0289-4196-92d4-ced99ec4191e',
                description: 'MAS repo validation card for Nala tests',
                newDescription: 'New Test Description',
            },
            browserParams: '#query=',
            tags: '@mas-studio @ccd @ccd-suggested @ccd-suggested-discard',
        },
        {
            tcid: '3',
            name: '@studio-suggested-discard-edited-mnemonic',
            path: '/studio.html',
            data: {
                cardid: '206a8742-0289-4196-92d4-ced99ec4191e',
                iconURL:
                    'https://www.adobe.com/content/dam/shared/images/product-icons/svg/photoshop.svg',
                newIconURL:
                    'https://www.adobe.com/content/dam/shared/images/product-icons/svg/illustrator.svg',
            },
            browserParams: '#query=',
            tags: '@mas-studio @ccd @ccd-suggested @ccd-suggested-discard',
        },
        {
            tcid: '4',
            name: '@studio-suggested-discard-edited-background',
            path: '/studio.html',
            data: {
                cardid: '206a8742-0289-4196-92d4-ced99ec4191e',
                newBackgroundURL:
                    'https://main--milo--adobecom.aem.page/assets/img/commerce/media_1d63dab9ee1edbf371d6f0548516c9e12b3ea3ff4.png',
            },
            browserParams: '#query=',
            tags: '@mas-studio @ccd @ccd-suggested @ccd-suggested-discard',
        },
        {
            tcid: '5',
            name: '@studio-suggested-discard-edited-price',
            path: '/studio.html',
            data: {
                cardid: '206a8742-0289-4196-92d4-ced99ec4191e',
                price: 'US$17.24/mo',
                strikethroughPrice: 'US$34.49/mo',
                newPrice: 'US$17.24/moper license',
                newStrikethroughPrice: 'US$34.49/moper license',
            },
            browserParams: '#query=',
            tags: '@mas-studio @ccd @ccd-suggested @ccd-suggested-discard',
        },
        {
            tcid: '6',
            name: '@studio-suggested-discard-edited-cta-ost',
            path: '/studio.html',
            data: {
                cardid: '206a8742-0289-4196-92d4-ced99ec4191e',
                ctaText: 'Buy now',
                newCtaText: 'Save now',
            },
            browserParams: '#query=',
            tags: '@mas-studio @ccd @ccd-suggested @ccd-suggested-discard',
        },
        {
            tcid: '7',
            name: '@studio-suggested-discard-edited-cta-label',
            path: '/studio.html',
            data: {
                cardid: '206a8742-0289-4196-92d4-ced99ec4191e',
                ctaText: 'Buy now',
                newCtaText: 'Buy now 2',
            },
            browserParams: '#query=',
            tags: '@mas-studio @ccd @ccd-suggested @ccd-suggested-discard',
        },
        {
            tcid: '8',
            name: '@studio-suggested-discard-edited-variant-change',
            path: '/studio.html',
            data: {
                cardid: '206a8742-0289-4196-92d4-ced99ec4191e',
            },
            browserParams: '#query=',
            tags: '@mas-studio @ccd @ccd-suggested @ccd-suggested-discard',
        },
        {
            tcid: '9',
            name: '@studio-suggested-discard-edited-osi',
            path: '/studio.html',
            data: {
                cardid: 'cc85b026-240a-4280-ab41-7618e65daac4',
                osi: 'A1xn6EL4pK93bWjM8flffQpfEL-bnvtoQKQAvkx574M',
                productCodeTag: 'product_code/phsp',
                offerTypeTag: 'offer_type/base',
                marketSegmentsTag: 'market_segments/com',
                planTypeTag: 'plan_type/abm',
                newosi: '1RwmqQ0NVsrtYr1bj05lZCJBavU6JGa67djrwKE8k8o',
                newPlanTypeTag: 'plan_type/puf',
                newOfferTypeTag: 'offer_type/trial',
                newMarketSegmentsTag: 'market_segments/edu',
            },
            browserParams: '#query=',
            tags: '@mas-studio @ccd @ccd-suggested @ccd-suggested-discard',
        },
        {
            tcid: '10',
            name: '@studio-suggested-discard-edited-cta-variant',
            path: '/studio.html',
            data: {
                cardid: '206a8742-0289-4196-92d4-ced99ec4191e',
                variant: 'primary-outline',
                newVariant: 'accent',
            },
            browserParams: '#query=',
            tags: '@mas-studio @ccd @ccd-suggested @ccd-suggested-discard',
        },
        {
            tcid: '11',
            name: '@studio-suggested-discard-edit-cta-checkout-params',
            path: '/studio.html',
            data: {
                cardid: '206a8742-0289-4196-92d4-ced99ec4191e',
                osi: 'A1xn6EL4pK93bWjM8flffQpfEL-bnvtoQKQAvkx574M',
                checkoutParams: {
                    mv: '1',
                    cs: 'individual',
                    promoid: 'ABC123',
                    mv2: '2',
                },
            },
            browserParams: '#query=',
            tags: '@mas-studio @ccd @ccd-suggested @ccd-suggested-discard',
        },
    ],
};
