export default {
    FeatureName: 'M@S Studio CCD Suggested',
    features: [
        {
            tcid: '0',
            name: '@studio-suggested-remove-correct-fragment',
            path: '/studio.html',
            data: {
                cardid: 'cc85b026-240a-4280-ab41-7618e65daac4',
            },
            browserParams: '#query=',
            tags: '@mas-studio @ccd @ccd-suggested @ccd-suggested-save',
        },
        {
            tcid: '1',
            name: '@studio-suggested-save-variant-change-to-slice',
            path: '/studio.html',
            data: {
                cardid: 'cc85b026-240a-4280-ab41-7618e65daac4',
                osi: 'A1xn6EL4pK93bWjM8flffQpfEL-bnvtoQKQAvkx574M',
            },
            browserParams: '#query=',
            tags: '@mas-studio @ccd @ccd-suggested @ccd-suggested-save',
        },
        {
            tcid: '2',
            name: '@studio-suggested-save-variant-change-to-trybuywidget',
            path: '/studio.html',
            data: {
                cardid: 'cc85b026-240a-4280-ab41-7618e65daac4',
                osi: 'A1xn6EL4pK93bWjM8flffQpfEL-bnvtoQKQAvkx574M',
            },
            browserParams: '#query=',
            tags: '@mas-studio @ccd @ccd-suggested @ccd-suggested-save',
        },
        {
            tcid: '3',
            name: '@studio-suggested-save-edited-title',
            path: '/studio.html',
            data: {
                cardid: 'cc85b026-240a-4280-ab41-7618e65daac4',
                title: 'Field Edit & Save',
                newTitle: 'Cloned Field Edit',
            },
            browserParams: '#query=',
            tags: '@mas-studio @ccd @ccd-suggested @ccd-suggested-save',
        },
        {
            tcid: '4',
            name: '@studio-suggested-save-edited-eyebrow',
            path: '/studio.html',
            data: {
                cardid: 'cc85b026-240a-4280-ab41-7618e65daac4',
                subtitle: 'do not edit',
                newSubtitle: 'New Subtitle',
            },
            browserParams: '#query=',
            tags: '@mas-studio @ccd @ccd-suggested @ccd-suggested-save',
        },
        {
            tcid: '5',
            name: '@studio-suggested-save-edited-mnemonic',
            path: '/studio.html',
            data: {
                cardid: 'cc85b026-240a-4280-ab41-7618e65daac4',
                iconURL:
                    'https://www.adobe.com/content/dam/shared/images/product-icons/svg/photoshop.svg',
                newIconURL:
                    'https://www.adobe.com/content/dam/shared/images/product-icons/svg/illustrator.svg',
            },
            browserParams: '#query=',
            tags: '@mas-studio @ccd @ccd-suggested @ccd-suggested-save',
        },
        {
            tcid: '6',
            name: '@studio-suggested-save-edited-description',
            path: '/studio.html',
            data: {
                cardid: 'cc85b026-240a-4280-ab41-7618e65daac4',
                description: 'MAS repo validation card for Nala tests',
                newDescription: 'New Test Description',
            },
            browserParams: '#query=',
            tags: '@mas-studio @ccd @ccd-suggested @ccd-suggested-save',
        },
        {
            tcid: '7',
            name: '@studio-suggested-save-edited-image',
            path: '/studio.html',
            data: {
                cardid: 'cc85b026-240a-4280-ab41-7618e65daac4',
                newBackgroundURL:
                    'https://main--milo--adobecom.aem.page/assets/img/commerce/media_1d63dab9ee1edbf371d6f0548516c9e12b3ea3ff4.png',
            },
            browserParams: '#query=',
            tags: '@mas-studio @ccd @ccd-suggested @ccd-suggested-save',
        },
        {
            tcid: '8',
            name: '@studio-suggested-save-edited-price',
            path: '/studio.html',
            data: {
                cardid: 'cc85b026-240a-4280-ab41-7618e65daac4',
                price: 'US$17.24/mo',
                strikethroughPrice: 'US$34.49/mo',
            },
            browserParams: '#query=',
            tags: '@mas-studio @ccd @ccd-suggested @ccd-suggested-save',
        },
        {
            tcid: '9',
            name: '@studio-suggested-save-edited-cta-label',
            path: '/studio.html',
            data: {
                cardid: 'cc85b026-240a-4280-ab41-7618e65daac4',
                ctaText: 'Buy now',
                newCtaText: 'Buy now 2',
            },
            browserParams: '#query=',
            tags: '@mas-studio @ccd @ccd-suggested @ccd-suggested-save',
        },
        {
            tcid: '10',
            name: '@studio-suggested-save-edited-osi',
            path: '/studio.html',
            data: {
                cardid: 'cc85b026-240a-4280-ab41-7618e65daac4',
                osi: 'A1xn6EL4pK93bWjM8flffQpfEL-bnvtoQKQAvkx574M',
                productCodeTag: 'product_code/phsp',
                offerTypeTag: 'offer_type/base',
                marketSegmentsTag: 'market_segments/com',
                planTypeTag: 'plan_type/abm',
                newosi: '1RwmqQ0NVsrtYr1bj05lZCJBavU6JGa67djrwKE8k8o',
                newPlanTypeTag: 'plan_type/puf',
                newOfferTypeTag: 'offer_type/trial',
                newMarketSegmentsTag: 'market_segments/edu',
            },
            browserParams: '#query=',
            tags: '@mas-studio @ccd @ccd-suggested @ccd-suggested-save',
        },
        {
            tcid: '11',
            name: '@studio-suggested-save-edited-cta-variant',
            path: '/studio.html',
            data: {
                cardid: 'cc85b026-240a-4280-ab41-7618e65daac4',
                osi: 'A1xn6EL4pK93bWjM8flffQpfEL-bnvtoQKQAvkx574M',
                variant: 'primary-outline',
                ctaCSS: {
                    color: 'rgb(34, 34, 34)',
                },
                newVariant: 'accent',
                newCtaCSS: {
                    'background-color': 'rgb(2, 101, 220)',
                    color: 'rgb(255, 255, 255)',
                },
            },
            browserParams: '#query=',
            tags: '@mas-studio @ccd @ccd-suggested @ccd-suggested-save',
        },
        {
            tcid: '12',
            name: '@studio-suggested-save-edited-cta-checkout-params',
            path: '/studio.html',
            data: {
                cardid: 'cc85b026-240a-4280-ab41-7618e65daac4',
                osi: 'A1xn6EL4pK93bWjM8flffQpfEL-bnvtoQKQAvkx574M',
                checkoutParams: {
                    mv: '1',
                    promoid: 'ABC123',
                    mv2: '2',
                },
            },
            browserParams: '#query=',
            tags: '@mas-studio @ccd @ccd-suggested @ccd-suggested-save',
        },
        {
            tcid: '13',
            name: '@studio-suggested-save-edited-analytics-ids',
            path: '/studio.html',
            data: {
                cardid: 'cc85b026-240a-4280-ab41-7618e65daac4',
                analyticsID: 'buy-now',
                daaLL: 'buy-now-1',
                daaLH: 'phsp',
                newAnalyticsID: 'save-now',
                newDaaLL: 'save-now-1',
            },
            browserParams: '#query=',
            tags: '@mas-studio @ccd @ccd-suggested @ccd-suggested-save',
        },
    ],
};
