export default {
    FeatureName: 'M@S Studio AHome Try Buy Widget',
    features: [
        {
            tcid: '0',
            name: '@studio-try-buy-widget-editor',
            path: '/studio.html',
            data: {
                cardid: '02ee0d3c-a472-44a1-b15a-f65c24eefc4b',
            },
            browserParams: '#query=',
            tags: '@mas-studio @ahome @ahome-try-buy-widget @ahome-try-buy-widget-edit nopr',
        },
        {
            tcid: '1',
            name: '@studio-try-buy-widget-edit-title',
            path: '/studio.html',
            data: {
                cardid: '02ee0d3c-a472-44a1-b15a-f65c24eefc4b',
                oldTitle: 'Automation Test',
                updatedTitle: 'Creative Cloud All Apps Long title test example',
                newTitle: 'Creative Cloud All Apps Long title te...',
            },
            browserParams: '#query=',
            tags: '@mas-studio @ahome @ahome-try-buy-widget @ahome-try-buy-widget-edit',
        },
        {
            tcid: '2',
            name: '@studio-try-buy-widget-edit-bg-color',
            path: '/studio.html',
            data: {
                cardid: '02ee0d3c-a472-44a1-b15a-f65c24eefc4b',
                originalBgColor: 'gray',
                updatedBgColor: 'Default',
            },
            browserParams: '#query=',
            tags: '@mas-studio @ahome @ahome-try-buy-widget @ahome-try-buy-widget-edit',
        },
        {
            tcid: '3',
            name: '@studio-try-buy-widget-edit-border-color',
            path: '/studio.html',
            data: {
                cardid: '02ee0d3c-a472-44a1-b15a-f65c24eefc4b',
                originalBorderColor: 'Transparent',
                updatedBorderColor: 'Gray 700',
                originalBorderCSSColor: 'rgba(0, 0, 0, 0)',
                updatedBorderCSSColor: 'rgb(70, 70, 70)',
            },
            browserParams: '#query=',
            tags: '@mas-studio @ahome @ahome-try-buy-widget @ahome-try-buy-widget-edit',
        },
        {
            tcid: '4',
            name: '@studio-try-buy-widget-edit-description',
            path: '/studio.html',
            data: {
                cardid: '02ee0d3c-a472-44a1-b15a-f65c24eefc4b',
                description: 'AHome Original Automation Test Card',
                updatedDescription: 'AHome Updated Automation Test Card',
            },
            browserParams: '#query=',
            tags: '@mas-studio @ahome @ahome-try-buy-widget @ahome-try-buy-widget-edit',
        },
        {
            tcid: '5',
            name: '@studio-try-buy-widget-edit-mnemonic',
            path: '/studio.html',
            data: {
                cardid: '02ee0d3c-a472-44a1-b15a-f65c24eefc4b',
                iconURL:
                    'https://www.adobe.com/cc-shared/assets/img/product-icons/svg/photoshop.svg',
                newIconURL:
                    'https://www.adobe.com/content/dam/shared/images/product-icons/svg/illustrator.svg',
            },
            browserParams: '#query=',
            tags: '@mas-studio @ahome @ahome-try-buy-widget @ahome-try-buy-widget-edit',
        },
        {
            tcid: '6',
            name: '@studio-try-buy-widget-edit-image',
            path: '/studio.html',
            data: {
                cardid: 'a07239e9-7216-403c-b1ee-3b1d0982a64b',
                backgroundURL:
                    'https://main--milo--adobecom.hlx.live/assets/img/commerce/media_1305cc40709da2533a0133ba8d920662e65925fc1.png?nocache=1740437377436',
                newBackgroundURL:
                    'https://milo.adobe.com/assets/img/commerce/media_158c1c22b1322dd28d7912d30fb27f29aa79f79b1.png',
            },
            browserParams: '#query=',
            tags: '@mas-studio @ahome @ahome-try-buy-widget @ahome-try-buy-widget-edit',
        },
        {
            tcid: '7',
            name: '@studio-try-buy-widget-edit-price',
            path: '/studio.html',
            data: {
                cardid: '02ee0d3c-a472-44a1-b15a-f65c24eefc4b',
                price: 'US$22.99/mo',
                newPrice: 'US$22.99/moper license',
                abmText: 'Annual, billed monthly',
            },
            browserParams: '#query=',
            tags: '@mas-studio @ahome @ahome-try-buy-widget @ahome-try-buy-widget-edit',
        },
        {
            tcid: '8',
            name: '@studio-try-buy-widget-edit-cta',
            path: '/studio.html',
            data: {
                cardid: '02ee0d3c-a472-44a1-b15a-f65c24eefc4b',
                ctaText: 'Free trial',
                newCtaText: 'Save now',
                osi: 'A1xn6EL4pK93bWjM8flffQpfEL-bnvtoQKQAvkx574M',
                ucv3: 'commerce.adobe.com/store/email',
                country: 'US',
                ctx: 'fp',
                lang: 'en',
                client: 'adobe_com',
            },
            browserParams: '#query=',
            tags: '@mas-studio @ahome @ahome-try-buy-widget @ahome-try-buy-widget-edit',
        },
        {
            tcid: '9',
            name: '@studio-try-buy-widget-change-to-slice',
            path: '/studio.html',
            data: {
                cardid: '02ee0d3c-a472-44a1-b15a-f65c24eefc4b',
                osi: 'A1xn6EL4pK93bWjM8flffQpfEL-bnvtoQKQAvkx574M',
            },
            browserParams: '#query=',
            tags: '@mas-studio @ahome @ahome-try-buy-widget @ahome-try-buy-widget-edit',
        },
        {
            tcid: '10',
            name: '@studio-try-buy-widget-change-to-suggested',
            path: '/studio.html',
            data: {
                cardid: '02ee0d3c-a472-44a1-b15a-f65c24eefc4b',
                osi: 'A1xn6EL4pK93bWjM8flffQpfEL-bnvtoQKQAvkx574M',
            },
            browserParams: '#query=',
            tags: '@mas-studio @ahome @ahome-try-buy-widget @ahome-try-buy-widget-edit',
        },
        {
            tcid: '11',
            name: '@studio-try-buy-widget-add-osi',
            path: '/studio.html',
            data: {
                cardid: '02ee0d3c-a472-44a1-b15a-f65c24eefc4b',
                osi: 'Mutn1LYoGojkrcMdCLO7LQlx1FyTHw27ETsfLv0h8DQ',
                productCodeTag: 'product_code/ccsn',
                offerTypeTag: 'offer_type/base',
                marketSegmentsTag: 'market_segments/com',
                planTypeTag: 'plan_type/abm',
            },
            browserParams: '#query=',
            tags: '@mas-studio @ahome @ahome-try-buy-widget @ahome-try-buy-widget-edit',
        },
        {
            tcid: '12',
            name: '@studio-try-buy-widget-edit-osi',
            path: '/studio.html',
            data: {
                cardid: '2d9025f7-ea56-4eeb-81b2-a52762358b9d',
                osi: 'Mutn1LYoGojkrcMdCLO7LQlx1FyTHw27ETsfLv0h8DQ',
                productCodeTag: 'product_code/ccsn',
                offerTypeTag: 'offer_type/base',
                marketSegmentsTag: 'market_segments/com',
                planTypeTag: 'plan_type/abm',
                newosi: '1RwmqQ0NVsrtYr1bj05lZCJBavU6JGa67djrwKE8k8o',
                newPlanTypeTag: 'plan_type/puf',
                newOfferTypeTag: 'offer_type/trial',
                newMarketSegmentsTag: 'market_segments/edu',
            },
            browserParams: '#query=',
            tags: '@mas-studio @ahome @ahome-try-buy-widget @ahome-try-buy-widget-edit',
        },
        {
            tcid: '13',
            name: '@studio-try-buy-widget-edit-cta-variant',
            path: '/studio.html',
            data: {
                cardid: '02ee0d3c-a472-44a1-b15a-f65c24eefc4b',
                variant: 'secondary',
                osi: 'A1xn6EL4pK93bWjM8flffQpfEL-bnvtoQKQAvkx574M',
                ctaCSS: {
                    'background-color': 'rgb(230, 230, 230)',
                    color: 'rgb(34, 34, 34)',
                },
                newVariant: 'secondary-outline',
                newCtaCSS: {
                    'background-color': 'rgba(0, 0, 0, 0)',
                    color: 'rgb(34, 34, 34)',
                },
            },
            browserParams: '#query=',
            tags: '@mas-studio @ahome @ahome-try-buy-widget @ahome-try-buy-widget-edit',
        },
    ],
};
