export default {
    FeatureName: 'M@S Studio ACOM Plans Individuals',
    features: [
        {
            tcid: '0',
            name: '@studio-plans-individuals-discard-edited-variant-change',
            path: '/studio.html',
            data: {
                cardid: '2cbfced4-111c-4099-ae9e-65e2c16d8e69',
            },
            browserParams: '#query=',
            tags: '@mas-studio @acom @acom-plans @acom-plans-individuals @acom-plans-individuals-discard',
        },
        {
            tcid: '1',
            name: '@studio-plans-individuals-discard-edited-size',
            path: '/studio.html',
            data: {
                cardid: '2cbfced4-111c-4099-ae9e-65e2c16d8e69',
            },
            browserParams: '#query=',
            tags: '@mas-studio @acom @acom-plans @acom-plans-individuals @acom-plans-individuals-discard',
        },
        {
            tcid: '2',
            name: '@studio-plans-individuals-discard-edited-title',
            path: '/studio.html',
            data: {
                cardid: '2cbfced4-111c-4099-ae9e-65e2c16d8e69',
                title: 'MAS Automation Test Card',
                newTitle: 'Change title',
            },
            browserParams: '#query=',
            tags: '@mas-studio @acom @acom-plans @acom-plans-individuals @acom-plans-individuals-discard',
        },
        {
            tcid: '3',
            name: '@studio-plans-individuals-discard-edited-badge',
            path: '/studio.html',
            data: {
                cardid: '2cbfced4-111c-4099-ae9e-65e2c16d8e69',
                badge: 'DO NOT EDIT',
                newBadge: 'Change badge',
            },
            browserParams: '#query=',
            tags: '@mas-studio @acom @acom-plans @acom-plans-individuals @acom-plans-individuals-discard',
        },
        {
            tcid: '4',
            name: '@studio-plans-individuals-discard-edited-description',
            path: '/studio.html',
            data: {
                cardid: '2cbfced4-111c-4099-ae9e-65e2c16d8e69',
                description: 'Edit and organize photos. Save 25% for the first 6 months. Ends Feb 26.',
                newDescription: 'New Test Description',
            },
            browserParams: '#query=',
            tags: '@mas-studio @acom @acom-plans @acom-plans-individuals @acom-plans-individuals-discard',
        },
        {
            tcid: '5',
            name: '@studio-plans-individuals-discard-edited-mnemonic',
            path: '/studio.html',
            data: {
                cardid: '2cbfced4-111c-4099-ae9e-65e2c16d8e69',
                iconURL: 'https://www.adobe.com/content/dam/shared/images/product-icons/svg/illustrator.svg',
                newIconURL: 'https://www.adobe.com/content/dam/shared/images/product-icons/svg/photoshop.svg',
            },
            browserParams: '#query=',
            tags: '@mas-studio @acom @acom-plans @acom-plans-individuals @acom-plans-individuals-discard',
        },
        {
            tcid: '6',
            name: '@studio-plans-individuals-discard-edited-callout',
            path: '/studio.html',
            data: {
                cardid: '2cbfced4-111c-4099-ae9e-65e2c16d8e69',
                calloutText: 'AI Assistant add-on available',
                newCalloutText: 'New callout text',
            },
            browserParams: '#query=',
            tags: '@mas-studio @acom @acom-plans @acom-plans-individuals @acom-plans-individuals-discard',
        },
        {
            tcid: '7',
            name: '@studio-plans-individuals-discard-edited-promo-text',
            path: '/studio.html',
            data: {
                cardid: '2cbfced4-111c-4099-ae9e-65e2c16d8e69',
                promoText: 'Test promotion text',
                newPromoText: 'New Promo Text',
            },
            browserParams: '#query=',
            tags: '@mas-studio @acom @acom-plans @acom-plans-individuals @acom-plans-individuals-discard',
        },
        {
            tcid: '8',
            name: '@studio-plans-individuals-discard-edited-price',
            path: '/studio.html',
            data: {
                cardid: '2cbfced4-111c-4099-ae9e-65e2c16d8e69',
                price: 'US$17.24/mo',
                strikethroughPrice: 'US$34.49/mo',
                newPrice: 'US$17.24/moper license',
                newStrikethroughPrice: 'US$34.49/moper license',
            },
            browserParams: '#query=',
            tags: '@mas-studio @acom @acom-plans @acom-plans-individuals @acom-plans-individuals-discard',
        },
        {
            tcid: '9',
            name: '@studio-plans-individuals-discard-edited-osi',
            path: '/studio.html',
            data: {
                cardid: '2cbfced4-111c-4099-ae9e-65e2c16d8e69',
                osi: 'yIcVsmjmQCHKQ-TvUJxH3-kop4ifvwoMBBzVg3qfaTg',
                offerTypeTag: 'offer_type/base',
                marketSegmentsTag: 'market_segments/com',
                planTypeTag: 'plan_type/m2m',
                newosi: '1RwmqQ0NVsrtYr1bj05lZCJBavU6JGa67djrwKE8k8o',
                newPlanTypeTag: 'plan_type/puf',
                newOfferTypeTag: 'offer_type/trial',
                newMarketSegmentsTag: 'market_segments/edu',
            },
            browserParams: '#query=',
            tags: '@mas-studio @acom @acom-plans @acom-plans-individuals @acom-plans-individuals-discard',
        },
        {
            tcid: '10',
            name: '@studio-plans-individuals-discard-edited-stock-checkbox',
            path: '/studio.html',
            data: {
                cardid: '2cbfced4-111c-4099-ae9e-65e2c16d8e69',
            },
            browserParams: '#query=',
            tags: '@mas-studio @acom @acom-plans @acom-plans-individuals @acom-plans-individuals-discard @nopr',
        },
        {
            tcid: '11',
            name: '@studio-plans-individuals-discard-edited-quantity-selector',
            path: '/studio.html',
            data: {
                cardid: '2cbfced4-111c-4099-ae9e-65e2c16d8e69',
            },
            browserParams: '#query=',
            tags: '@mas-studio @acom @acom-plans @acom-plans-individuals @acom-plans-individuals-discard',
        },
        {
            tcid: '12',
            name: '@studio-plans-individuals-discard-edited-whats-included',
            path: '/studio.html',
            data: {
                cardid: '2cbfced4-111c-4099-ae9e-65e2c16d8e69',
                whatsIncludedText: 'List of items:',
            },
            browserParams: '#query=',
            tags: '@mas-studio @acom @acom-plans @acom-plans-individuals @acom-plans-individuals-discard',
        },
        {
            tcid: '13',
            name: '@studio-plans-individuals-discard-edited-badge-color',
            path: '/studio.html',
            data: {
                cardid: '2cbfced4-111c-4099-ae9e-65e2c16d8e69',
                color: 'Yellow 300',
                colorCSS: 'rgb(245, 199, 0)',
                newColor: 'Green 900',
            },
            browserParams: '#query=',
            tags: '@mas-studio @acom @acom-plans @acom-plans-individuals @acom-plans-individuals-discard',
        },
        {
            tcid: '14',
            name: '@studio-plans-individuals-discard-edited-badge-border-color',
            path: '/studio.html',
            data: {
                cardid: '2cbfced4-111c-4099-ae9e-65e2c16d8e69',
                color: 'Yellow 300',
                colorCSS: 'rgb(245, 199, 0)',
                newColor: 'Green 900',
            },
            browserParams: '#query=',
            tags: '@mas-studio @acom @acom-plans @acom-plans-individuals @acom-plans-individuals-discard',
        },
        {
            tcid: '15',
            name: '@studio-plans-individuals-discard-edited-card-border-color',
            path: '/studio.html',
            data: {
                cardid: '2cbfced4-111c-4099-ae9e-65e2c16d8e69',
                color: 'Yellow 300',
                colorCSS: 'rgb(245, 199, 0)',
                newColor: 'Gray 300',
            },
            browserParams: '#query=',
            tags: '@mas-studio @acom @acom-plans @acom-plans-individuals @acom-plans-individuals-discard',
        },
        {
            tcid: '16',
            name: '@studio-plans-individuals-discard-edited-cta-ost',
            path: '/studio.html',
            data: {
                cardid: '2cbfced4-111c-4099-ae9e-65e2c16d8e69',
                osi: 'yIcVsmjmQCHKQ-TvUJxH3-kop4ifvwoMBBzVg3qfaTg',
                ctaText: 'Buy now',
                newCtaOption: 'Save now',
                newCtaText: 'save-now',
                ucv3: 'commerce.adobe.com/store/email',
                country: 'US',
                ctx: 'fp',
                lang: 'en',
                client: 'adobe_com',
                promo: 'FY25PLES256MROW',
            },
            browserParams: '#query=',
            tags: '@mas-studio @acom @acom-plans @acom-plans-individuals @acom-plans-individuals-discard',
        },
        {
            tcid: '17',
            name: '@studio-plans-individuals-discard-edited-cta-label',
            path: '/studio.html',
            data: {
                cardid: '2cbfced4-111c-4099-ae9e-65e2c16d8e69',
                osi: 'yIcVsmjmQCHKQ-TvUJxH3-kop4ifvwoMBBzVg3qfaTg',
                ctaText: 'Buy now',
                newCtaText: 'Buy now 2',
            },
            browserParams: '#query=',
            tags: '@mas-studio @acom @acom-plans @acom-plans-individuals @acom-plans-individuals-discard',
        },
        {
            tcid: '18',
            name: '@studio-plans-individuals-discard-edited-cta-variant',
            path: '/studio.html',
            data: {
                cardid: '2cbfced4-111c-4099-ae9e-65e2c16d8e69',
                osi: 'yIcVsmjmQCHKQ-TvUJxH3-kop4ifvwoMBBzVg3qfaTg',
                variant: 'accent',
                ctaCSS: {
                    'background-color': 'rgb(59, 99, 251)',
                    color: 'rgb(255, 255, 255)',
                },
                newCtaCSS: {
                    color: 'rgb(44, 44, 44)',
                },
                newVariant: 'primary-outline',
            },
            browserParams: '#query=',
            tags: '@mas-studio @acom @acom-plans @acom-plans-individuals @acom-plans-individuals-discard',
        },
        {
            tcid: '19',
            name: '@studio-plans-individuals-discard-edited-cta-checkout-params',
            path: '/studio.html',
            data: {
                cardid: '2cbfced4-111c-4099-ae9e-65e2c16d8e69',
                osi: 'yIcVsmjmQCHKQ-TvUJxH3-kop4ifvwoMBBzVg3qfaTg',
                checkoutParams: {
                    mv: '1',
                    promoid: 'ABC123',
                    mv2: '2',
                },
            },
            browserParams: '#query=',
            tags: '@mas-studio @acom @acom-plans @acom-plans-individuals @acom-plans-individuals-discard',
        },
    ],
};
