export default {
    FeatureName: 'M@S Studio ACOM Plans Individuals',
    features: [
        {
            tcid: '0',
            name: '@studio-plans-individuals-save-edited-variant-change',
            path: '/studio.html',
            data: {
                cardid: '6f189be0-d64b-468f-b340-92888206cce8',
            },
            browserParams: '#query=',
            tags: '@mas-studio @acom @acom-plans @acom-plans-individuals @acom-plans-individuals-save',
        },
        {
            tcid: '1',
            name: '@studio-plans-individuals-save-edited-size',
            path: '/studio.html',
            data: {
                cardid: '6f189be0-d64b-468f-b340-92888206cce8',
            },
            browserParams: '#query=',
            tags: '@mas-studio @acom @acom-plans @acom-plans-individuals @acom-plans-individuals-save',
        },
        {
            tcid: '2',
            name: '@studio-plans-individuals-save-edited-title',
            path: '/studio.html',
            data: {
                cardid: '6f189be0-d64b-468f-b340-92888206cce8',
                title: 'Field Edit & Save',
                newTitle: 'Change title',
            },
            browserParams: '#query=',
            tags: '@mas-studio @acom @acom-plans @acom-plans-individuals @acom-plans-individuals-save',
        },
        {
            tcid: '3',
            name: '@studio-plans-individuals-save-edited-badge',
            path: '/studio.html',
            data: {
                cardid: '6f189be0-d64b-468f-b340-92888206cce8',
                badge: 'DO NOT EDIT',
                newBadge: 'Change badge',
            },
            browserParams: '#query=',
            tags: '@mas-studio @acom @acom-plans @acom-plans-individuals @acom-plans-individuals-save',
        },
        {
            tcid: '4',
            name: '@studio-plans-individuals-save-edited-description',
            path: '/studio.html',
            data: {
                cardid: '6f189be0-d64b-468f-b340-92888206cce8',
                description: 'MAS Automation Test card.',
                newDescription: 'New Test Description',
            },
            browserParams: '#query=',
            tags: '@mas-studio @acom @acom-plans @acom-plans-individuals @acom-plans-individuals-save',
        },
        {
            tcid: '5',
            name: '@studio-plans-individuals-save-edited-mnemonic',
            path: '/studio.html',
            data: {
                cardid: '6f189be0-d64b-468f-b340-92888206cce8',
                iconURL:
                    'https://www.adobe.com/content/dam/shared/images/product-icons/svg/illustrator.svg',
                newIconURL:
                    'https://www.adobe.com/content/dam/shared/images/product-icons/svg/photoshop.svg',
            },
            browserParams: '#query=',
            tags: '@mas-studio @acom @acom-plans @acom-plans-individuals @acom-plans-individuals-save',
        },
        {
            tcid: '6',
            name: '@studio-plans-individuals-save-edited-callout',
            path: '/studio.html',
            data: {
                cardid: '6f189be0-d64b-468f-b340-92888206cce8',
                calloutText: 'AI Assistant add-on available',
            },
            browserParams: '#query=',
            tags: '@mas-studio @acom @acom-plans @acom-plans-individuals @acom-plans-individuals-save',
        },
        {
            tcid: '7',
            name: '@studio-plans-individuals-save-edited-promo-text',
            path: '/studio.html',
            data: {
                cardid: '6f189be0-d64b-468f-b340-92888206cce8',
                promoText: 'Test promotion text',
            },
            browserParams: '#query=',
            tags: '@mas-studio @acom @acom-plans @acom-plans-individuals @acom-plans-individuals-save',
        },
        {
            tcid: '8',
            name: '@studio-plans-individuals-save-edited-price',
            path: '/studio.html',
            data: {
                cardid: '6f189be0-d64b-468f-b340-92888206cce8',
                price: 'US$17.24/mo',
                strikethroughPrice: 'US$34.49/mo',
                newPrice: 'US$17.24/moper license',
                newStrikethroughPrice: 'US$34.49/moper license',
            },
            browserParams: '#query=',
            tags: '@mas-studio @acom @acom-plans @acom-plans-individuals @acom-plans-individuals-save',
        },
        {
            tcid: '9',
            name: '@studio-plans-individuals-save-edited-osi',
            path: '/studio.html',
            data: {
                cardid: '6f189be0-d64b-468f-b340-92888206cce8',
                osi: 'yIcVsmjmQCHKQ-TvUJxH3-kop4ifvwoMBBzVg3qfaTg',
                offerTypeTag: 'offer_type/base',
                marketSegmentsTag: 'market_segments/com',
                planTypeTag: 'plan_type/m2m',
                newosi: '1RwmqQ0NVsrtYr1bj05lZCJBavU6JGa67djrwKE8k8o',
                newPlanTypeTag: 'plan_type/puf',
                newOfferTypeTag: 'offer_type/trial',
                newMarketSegmentsTag: 'market_segments/edu',
            },
            browserParams: '#query=',
            tags: '@mas-studio @acom @acom-plans @acom-plans-individuals @acom-plans-individuals-save',
        },
        {
            tcid: '10',
            name: '@studio-plans-individuals-save-edited-stock-checkbox',
            path: '/studio.html',
            data: {
                cardid: '6f189be0-d64b-468f-b340-92888206cce8',
            },
            browserParams: '#query=',
            tags: '@mas-studio @acom @acom-plans @acom-plans-individuals @acom-plans-individuals-save',
        },
        {
            tcid: '11',
            name: '@studio-plans-individuals-save-edited-quantity-selector',
            path: '/studio.html',
            data: {
                cardid: '6f189be0-d64b-468f-b340-92888206cce8',
            },
            browserParams: '#query=',
            tags: '@mas-studio @acom @acom-plans @acom-plans-individuals @acom-plans-individuals-save',
        },
        {
            tcid: '12',
            name: '@studio-plans-individuals-save-edited-whats-included',
            path: '/studio.html',
            data: {
                cardid: '6f189be0-d64b-468f-b340-92888206cce8',
                whatsIncludedText: 'List of items:',
            },
            browserParams: '#query=',
            tags: '@mas-studio @acom @acom-plans @acom-plans-individuals @acom-plans-individuals-save',
        },
        {
            tcid: '13',
            name: '@studio-plans-individuals-save-edited-badge-color',
            path: '/studio.html',
            data: {
                cardid: '6f189be0-d64b-468f-b340-92888206cce8',
                color: 'Yellow 300',
                newColor: 'Green 900',
                newColorCSS: 'rgb(5, 131, 78)',
            },
            browserParams: '#query=',
            tags: '@mas-studio @acom @acom-plans @acom-plans-individuals @acom-plans-individuals-save',
        },
        {
            tcid: '14',
            name: '@studio-plans-individuals-save-edited-badge-border-color',
            path: '/studio.html',
            data: {
                cardid: '6f189be0-d64b-468f-b340-92888206cce8',
                color: 'Yellow 300',
                newColor: 'Green 900',
                newColorCSS: 'rgb(5, 131, 78)',
            },
            browserParams: '#query=',
            tags: '@mas-studio @acom @acom-plans @acom-plans-individuals @acom-plans-individuals-save',
        },
        {
            tcid: '15',
            name: '@studio-plans-individuals-save-edited-card-border-color',
            path: '/studio.html',
            data: {
                cardid: '6f189be0-d64b-468f-b340-92888206cce8',
                color: 'Yellow 300',
                newColor: 'Gray 300',
                newColorCSS: 'rgb(218, 218, 218)',
            },
            browserParams: '#query=',
            tags: '@mas-studio @acom @acom-plans @acom-plans-individuals @acom-plans-individuals-save',
        },
    ],
};
