export default {
    FeatureName: 'M@S Studio CCD Slice',
    features: [
        {
            tcid: '0',
            name: '@studio-slice-variant-change-to-suggested',
            path: '/studio.html',
            data: {
                cardid: '8cf16da3-a95d-4186-8a74-e0a2386631a6',
                osi: 'A1xn6EL4pK93bWjM8flffQpfEL-bnvtoQKQAvkx574M',
            },
            browserParams: '#query=',
            tags: '@mas-studio @ccd @ccd-slice @ccd-slice-edit',
        },
        {
            tcid: '1',
            name: '@studio-slice-edit-size',
            path: '/studio.html',
            data: {
                cardid: '8cf16da3-a95d-4186-8a74-e0a2386631a6',
            },
            browserParams: '#query=',
            tags: '@mas-studio @ccd @ccd-slice @ccd-slice-edit',
        },
        {
            tcid: '2',
            name: '@studio-slice-edit-badge',
            path: '/studio.html',
            data: {
                cardid: '8cf16da3-a95d-4186-8a74-e0a2386631a6',
                badge: 'DO NOT EDIT',
                newBadge: 'Change badge',
            },
            browserParams: '#query=',
            tags: '@mas-studio @ccd @ccd-slice @ccd-slice-edit',
        },
        {
            tcid: '3',
            name: '@studio-slice-edit-description',
            path: '/studio.html',
            data: {
                cardid: '8cf16da3-a95d-4186-8a74-e0a2386631a6',
                description: 'Automation Test Card',
                newDescription: 'New Test Description',
            },
            browserParams: '#query=',
            tags: '@mas-studio @ccd @ccd-slice @ccd-slice-edit',
        },
        {
            tcid: '4',
            name: '@studio-slice-edit-mnemonic',
            path: '/studio.html',
            data: {
                cardid: '8cf16da3-a95d-4186-8a74-e0a2386631a6',
                iconURL:
                    'https://www.adobe.com/content/dam/shared/images/product-icons/svg/photoshop.svg',
                newIconURL:
                    'https://www.adobe.com/content/dam/shared/images/product-icons/svg/illustrator.svg',
            },
            browserParams: '#query=',
            tags: '@mas-studio @ccd @ccd-slice @ccd-slice-edit',
        },
        {
            tcid: '5',
            name: '@studio-slice-edit-image',
            path: '/studio.html',
            data: {
                cardid: '8cf16da3-a95d-4186-8a74-e0a2386631a6',
                backgroundURL:
                    'https://milo.adobe.com/assets/img/commerce/media_10bef5ec21c22fd7fe201cb02735082df13bf4960.jpeg',
                newBackgroundURL:
                    'https://milo.adobe.com/assets/img/commerce/media_158c1c22b1322dd28d7912d30fb27f29aa79f79b1.png',
            },
            browserParams: '#query=',
            tags: '@mas-studio @ccd @ccd-slice @ccd-slice-edit',
        },
        {
            tcid: '6',
            name: '@studio-slice-edit-price',
            path: '/studio.html',
            data: {
                cardid: '8cf16da3-a95d-4186-8a74-e0a2386631a6',
                price: 'US$17.24/mo',
                strikethroughPrice: 'US$34.49/mo',
                newPrice: 'US$17.24/moper license',
                newStrikethroughPrice: 'US$34.49/moper license',
            },
            browserParams: '#query=',
            tags: '@mas-studio @ccd @ccd-slice @ccd-slice-edit',
        },
        {
            tcid: '7',
            name: '@studio-slice-edit-cta-ost',
            path: '/studio.html',
            data: {
                cardid: '8cf16da3-a95d-4186-8a74-e0a2386631a6',
                osi: 'A1xn6EL4pK93bWjM8flffQpfEL-bnvtoQKQAvkx574M',
                ctaText: 'Buy now',
                newCtaText: 'Save now',
                ucv3: 'commerce.adobe.com/store/email',
                country: 'US',
                ctx: 'fp',
                lang: 'en',
                client: 'adobe_com',
                promo: 'UMRM2MUSPr501YOC',
            },
            browserParams: '#query=',
            tags: '@mas-studio @ccd @ccd-slice @ccd-slice-edit',
        },
        {
            tcid: '8',
            name: '@studio-slice-edit-cta-label',
            path: '/studio.html',
            data: {
                cardid: '8cf16da3-a95d-4186-8a74-e0a2386631a6',
                osi: 'A1xn6EL4pK93bWjM8flffQpfEL-bnvtoQKQAvkx574M',
                ctaText: 'Buy now',
                newCtaText: 'Buy now 2',
            },
            browserParams: '#query=',
            tags: '@mas-studio @ccd @ccd-slice @ccd-slice-edit',
        },
        {
            tcid: '9',
            name: '@studio-slice-edit-price-promo',
            path: '/studio.html',
            data: {
                cardid: '8cf16da3-a95d-4186-8a74-e0a2386631a6',
                promo: 'UMRM2MUSPr501YOC',
                newPromo: 'testpromo',
            },
            browserParams: '#query=',
            tags: '@mas-studio @ccd @ccd-slice @ccd-slice-edit',
        },
        {
            tcid: '10',
            name: '@studio-slice-edit-cta-promo',
            path: '/studio.html',
            data: {
                cardid: '8cf16da3-a95d-4186-8a74-e0a2386631a6',
                promo: 'UMRM2MUSPr501YOC',
                newPromo: 'testpromo',
                ucv3: 'commerce.adobe.com/store/email',
                country: 'US',
                ctx: 'fp',
                lang: 'en',
                client: 'adobe_com',
            },
            browserParams: '#query=',
            tags: '@mas-studio @ccd @ccd-slice @ccd-slice-edit',
        },
        {
            tcid: '11',
            name: '@studio-slice-variant-change-to-trybuywidget',
            path: '/studio.html',
            data: {
                cardid: '8cf16da3-a95d-4186-8a74-e0a2386631a6',
                osi: 'A1xn6EL4pK93bWjM8flffQpfEL-bnvtoQKQAvkx574M',
            },
            browserParams: '#query=',
            tags: '@mas-studio @ccd @ccd-slice @ccd-slice-edit',
        },
        {
            tcid: '12',
            name: '@studio-slice-add-osi',
            path: '/studio.html',
            data: {
                cardid: '8cf16da3-a95d-4186-8a74-e0a2386631a6',
                osi: 'A1xn6EL4pK93bWjM8flffQpfEL-bnvtoQKQAvkx574M',
                productCodeTag: 'product_code/PHSP',
                offerTypeTag: 'offer_type/base',
                marketSegmentsTag: 'market_segments/com',
                planTypeTag: 'plan_type/abm',
            },
            browserParams: '#query=',
            tags: '@mas-studio @ccd @ccd-slice @ccd-slice-edit',
        },
        {
            tcid: '13',
            name: '@studio-slice-edit-osi',
            path: '/studio.html',
            data: {
                cardid: '3b1fb0f1-b74e-4e8f-81ad-1744012b1935',
                osi: 'A1xn6EL4pK93bWjM8flffQpfEL-bnvtoQKQAvkx574M',
                productCodeTag: 'product_code/PHSP',
                offerTypeTag: 'offer_type/base',
                marketSegmentsTag: 'market_segments/com',
                planTypeTag: 'plan_type/abm',
                newosi: '1RwmqQ0NVsrtYr1bj05lZCJBavU6JGa67djrwKE8k8o',
                newPlanTypeTag: 'plan_type/puf',
                newOfferTypeTag: 'offer_type/trial',
                newMarketSegmentsTag: 'market_segments/edu',
            },
            browserParams: '#query=',
            tags: '@mas-studio @ccd @ccd-slice @ccd-slice-edit',
        },
        {
            tcid: '14',
            name: '@studio-slice-edit-cta-variant',
            path: '/studio.html',
            data: {
                cardid: '8cf16da3-a95d-4186-8a74-e0a2386631a6',
                osi: 'A1xn6EL4pK93bWjM8flffQpfEL-bnvtoQKQAvkx574M',
                variant: 'accent',
                ctaCSS: {
                    'background-color': 'rgb(2, 101, 220)',
                    color: 'rgb(255, 255, 255)',
                },
                newVariant: 'primary-outline',
                newCtaCSS: {
                    color: 'rgb(34, 34, 34)',
                },
            },
            browserParams: '#query=',
            tags: '@mas-studio @ccd @ccd-slice @ccd-slice-edit',
        },
        {
            tcid: '15',
            name: '@studio-slice-edit-cta-checkout-params',
            path: '/studio.html',
            data: {
                cardid: '8cf16da3-a95d-4186-8a74-e0a2386631a6',
                osi: 'A1xn6EL4pK93bWjM8flffQpfEL-bnvtoQKQAvkx574M',
                checkoutParams: {
                    mv: '1',
                    cs: 'individual',
                    promoid: 'ABC123',
                    mv2: '2',
                },
            },
            browserParams: '#query=',
            tags: '@mas-studio @ccd @ccd-slice @ccd-slice-edit',
        },
    ],
};
