name: IO Studio Merge
on:
    pull_request:
        types: [closed]
        paths:
            - 'io/studio/**'

jobs:
    deploy_stage:
        if: github.event.pull_request.merged == true
        uses: ./.github/workflows/io-studio-deploy.yaml
        with:
            batch_size: 5
            rps_limit: 5
            worker_concurrency: 2
            vault-path: merch-at-scale/aio-studio/stage
        secrets: inherit

    test_stage:
        needs: deploy_stage
        uses: ./.github/workflows/io-studio-tests.yaml
        with:
            namespace: ${{ needs.deploy_stage.outputs.namespace }}

    deploy_production:
        needs: test_stage
        uses: ./.github/workflows/io-studio-deploy.yaml
        with:
            batch_size: 5
            rps_limit: 5
            worker_concurrency: 2
            vault-path: merch-at-scale/aio-studio/prod
        secrets: inherit

    test_production:
        needs: deploy_production
        uses: ./.github/workflows/io-studio-tests.yaml
        with:
            namespace: ${{ needs.deploy_production.outputs.namespace }}
